"""uuid column change to 28

Revision ID: 2a9af5c2deef
Revises: 3cbdbc51c578
Create Date: 2023-11-16 12:33:01.795095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a9af5c2deef"
down_revision: Union[str, None] = "3cbdbc51c578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "uid",
        existing_type=sa.BINARY(length=16),
        type_=sa.BINARY(length=28),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "uid",
        existing_type=sa.BINARY(length=28),
        type_=sa.BINARY(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
